apiVersion: v1
kind: Pod
metadata:
  name: greeter-client-round-robin
spec:
  containers:
  - name: greeter-client-round-robin
    image: wicharypawel/grpc-loadbalancing_greeter_client_round_robin:latest
    imagePullPolicy: Never
    env:
    #- name: GRPC_VERBOSITY
    #  value: "debug"
    #- name: GRPC_TRACE
    #  value: "all"
  restartPolicy: Never
