apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-dns-config
  namespace: default
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        rewrite name _grpclb._tcp.grpc-server.custom-dns.local _grpclb._tcp.grpc-server-balancer.default.svc.cluster.local
        rewrite name grpc-server.custom-dns.local grpc-server.default.svc.cluster.local
        file /etc/coredns/txtRecordsFile.db _grpc_config.grpc-server.custom-dns.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
  txtRecordsFile.db: |
    _grpc_config.grpc-server.custom-dns.local.     IN      SOA     sns.dns.icann.org. noc.dns.icann.org. 2015082541 7200 3600 1209600 3600
    _grpc_config.grpc-server.custom-dns.local.     IN      TXT     "grpc_config=[{\"serviceConfig\":{\"loadBalancingPolicy\":\"round_robin\",\"methodConfig\":[{\"name\":[{\"service\":\"MyService\",\"method\":\"Foo\"}],\"waitForReady\":true}]}}]"
---
apiVersion: v1
kind: Service
metadata:
  name: custom-dns
  namespace: default
  labels:
    app: custom-dns
spec:
  selector:
    app: custom-dns
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: custom-dns
  namespace: default
  labels:
    app: custom-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-dns
  template:
    metadata:
      labels:
        app: custom-dns
    spec:
      containers:
      - name: coredns
        image: coredns/coredns:1.6.9
        imagePullPolicy: Always
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: custom-dns-config
            items:
            - key: Corefile
              path: Corefile
            - key: txtRecordsFile.db
              path: txtRecordsFile.db
