apiVersion: v1
kind: Pod
metadata:
  name: go-grpc-client-lookaside
spec:
  containers:
  - name: go-grpc-client-lookaside
    image: go-grpc-client-lookaside:latest
    imagePullPolicy: Never
    #env:
    #- name: GRPC_GO_LOG_SEVERITY_LEVEL
    #  value: "info"
    #- name: GRPC_GO_LOG_VERBOSITY_LEVEL
    #  value: "2"
    #- name: GODEBUG
    #  value: "http2debug=2"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  restartPolicy: Never
