apiVersion: v1
kind: Pod
metadata:
  name: grpc-dotnet-client-xds
spec:
  containers:
  - name: grpc-dotnet-client-xds
    image: grpc-dotnet-client-xds:latest
    imagePullPolicy: Never
    env:
    - name: SERVICE_TARGET
      value: "xds://grpc-server.default.svc.cluster.local:8000"
    - name: GRPC_XDS_BOOTSTRAP
      value: "/app/XdsBootstrapFile.json"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  restartPolicy: Never
