apiVersion: v1
kind: Pod
metadata:
  name: grpc-csharp-client-lookaside
spec:
  containers:
  - name: grpc-csharp-client-lookaside
    image: grpc-csharp-client-lookaside:latest
    imagePullPolicy: Never
    env:
    - name: SERVICE_TARGET
      value: "grpc-server-balancer.default.svc.cluster.local:8000"
    # grpclb can only be used with "ares" DNS resolver
    - name: GRPC_DNS_RESOLVER
      value: "ares"
    #- name: GRPC_VERBOSITY
    #  value: "debug"
    #- name: GRPC_TRACE
    #  value: "all"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  restartPolicy: Never
