apiVersion: v1
kind: Service
metadata:
  name: grpc-server-balancer
spec:
  clusterIP: None  # Headless service
  ports:
  # Use port named "grpclb" to expose the needed DNS SRV record
  - name: grpclb
    port: 9000
  selector:
    app: grpc-server-balancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-balancer
spec:
  replicas: 2
  selector:
      matchLabels:
        app: grpc-server-balancer
  template:
    metadata:
      labels:
        app: grpc-server-balancer
    spec:
      containers:
      - name: grpc-server-balancer
        image: grpc-server-balancer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        env:
        - name: SIMPLEBALANCER_CLIENT_STATS_REPORT_INTERVAL
          value: "00:00:10"
        - name: SIMPLEBALANCER_ENABLE_LOADBALANCE_TOKENS
          value: "true"
        - name: SIMPLEBALANCER_K8S_SERVICE
          value: "name=grpc-server;namespace=default;alias=grpc-server.custom-dns.local;alias=grpc-server-balancer;alias=grpc-server-balancer.default.svc.cluster.local"
        - name: SIMPLEBALANCER_VALIDATE_SERVICE_NAME
          value: "true"
