apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  ports:
  - name: grpc
    port: 8000
  selector:
    app: grpc-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: grpc-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
