apiVersion: v1
kind: Pod
metadata:
  name: grpc-dotnet-client-sidecar-dynamic
spec:
  containers:
  - name: grpc-dotnet-client-sidecar-dynamic
    image: grpc-dotnet-client-sidecar:latest
    imagePullPolicy: Never
    env:
    - name: SERVICE_TARGET
      value: "http://grpc-server.default.svc.cluster.local:8000"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  restartPolicy: Never
