apiVersion: v1
kind: Pod
metadata:
  name: grpc-dotnet-client-lookaside-aspnet
spec:
  containers:
  - name: grpc-dotnet-client-lookaside-aspnet
    image: grpc-dotnet-client-lookaside-aspnet:latest
    imagePullPolicy: Never
    env:
    - name: SERVICE_TARGET
      value: "dns://grpc-server-balancer.default.svc.cluster.local:8000"
    ports:
      - containerPort: 5000
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  restartPolicy: Never
