apiVersion: v1
kind: Pod
metadata:
  name: java-grpc-client-lookaside
spec:
  containers:
  - name: java-grpc-client-lookaside
    image: java-grpc-client-lookaside:latest
    imagePullPolicy: Never
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  restartPolicy: Never
