apiVersion: v1
kind: Pod
metadata:
  name: python-grpc-client-lookaside
spec:
  containers:
  - name: python-grpc-client-lookaside
    image: python-grpc-client-lookaside:latest
    imagePullPolicy: Never
    env:
    - name: GRPC_DNS_RESOLVER
      value: "ares"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  restartPolicy: Never
