apiVersion: v1
kind: Pod
metadata:
  name: greeter-client-lookaside-lb
spec:
  containers:
  - name: greeter-client-lookaside-lb
    image: wicharypawel/grpc-loadbalancing_greeter_client:latest
    imagePullPolicy: Never
    env:
    # use the grpclb as a lookaside balancer
    - name: GREETER_SERVICE_TARGET
      value: "greeter-server-balancer.default.svc.cluster.local:8000"
    # grpclb can only be used with "ares" DNS resolver
    - name: GRPC_DNS_RESOLVER
      value: "ares"
    #- name: GRPC_VERBOSITY
    #  value: "debug"
    #- name: GRPC_TRACE
    #  value: "all"
  restartPolicy: Never
